### PR TITLE
Added points logic and timer

### LINKED ISSUE #8: Add points logic
- if the item goes in the right bin, you earn +10 (?) points
- if the item goes in the wrong bin, you lose -10 points.

### LINKED ISSUE #9: Add Item/Bin categorization
- If plastic bottle -> plastic bin
- If apple -> organic bin
- etc. 

- This is required for Issue #8

### LINKED ISSUE #12: Add timer (60 seconds)

### PR DESCRIPTION
**Pull request by diananova**
- closes #9 
- closes #8 

- points update on the screen

### CODE REVIEW

**Comment by diananova** [comment]
- closes #19 
- credits for the timer: https://medium.com/better-programming/building-a-simple-countdown-timer-with-react-4ca32763dda7

**Comment by diananova** [comment]
- ready to be merged
- the version with Matter.js is in the Matter branch in case we decide to have moving items

**Review by Rita-Okonkwo — APPROVED** [review]
lgtm

**Comment by Rita-Okonkwo** [comment]
I think your branch has conflicts with the master branch. Please resolve

**Pull request merged**
