### PR TITLE
Add Music Functionality

### LINKED ISSUE #21: Add music

### PR DESCRIPTION
**Pull request by Rita-Okonkwo**
Still working on the mute feature. Not ready for merge

### CODE REVIEW

**Review by diananova — APPROVED** [review]
Looks good so far!

**Comment by diananova** [comment]
- closes #39

**Comment by Rita-Okonkwo** [comment]
ready to merge

**Review by diananova — CHANGES_REQUESTED** [review]
- device used for tests: iPhone
- the music starts playing when I start the game! ✅
- but the mute button doesn't work, not sure why. Might be a device dependent issue? 
- I think the song starts playing every time I click start, so if you go back to menu and start the game, two songs are played contemporarily.

**Review by diananova — APPROVED** [review]
- Great! Now everything works.

**Pull request merged**
